ALTER TABLE "Post"
ADD COLUMN "gender" TEXT NOT NULL DEFAULT 'male',
ADD COLUMN "neutered" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Post"
ALTER COLUMN "gender" DROP DEFAULT,
ALTER COLUMN "neutered" DROP DEFAULT;
